parameters:
    # Adds a fallback API KEYS if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(CONDUCTION_COMMONGROUND_BAG_APIKEY): 'Change me your .env file'
    common_ground.bag.location: 'https://bag.basisregistraties.overheid.nl/api/v1/'
    common_ground.bag.apikey: 'e8a95365-3078-4b41-990a-e3de43cecd36'

common_ground:      
    bag:
        # cashing is a common ground hot patato, from a data at the source perspective we don't want to duplicate data
        # but.... city and street names are not going to change regularly, so to prevent unnecessary api calls cashing makes sense
        #
        # Therefore we are going to allow cashing on the bag api
        #
        # Valid values:
        # - false (no cashing)
        # - integer (cash for given amount of milliseconds)
        # - a valid php datetime input (cash item deleted at that date), https://www.php.net/manual/en/function.strtotime.php
        cash:        
            nummeraanduiding: 604800000 # 1 week      
            woonplaats: 'January 1st Next Year' # By law Dutch localities only change in January the first      
            openbareruimte:  604800000 # 1 week      
            panden: 604800000 # 1 week
            verblijfsobject: 604800000 # 1 week
            ligplaatsen: 604800000 # 1 week
            standplaatsen: 604800000 # 1 week
        # Get your BAG api key at https://bag.basisregistraties.overheid.nl/restful-api, or by sending a email to dataplatform@kadaster.nl        
        apikey: '%env(CONDUCTION_COMMONGROUND_BAG_APIKEY)%' 
        # The default BAG api location, change this if yoy are using an NLX adaptor
        location: 'https://bag.basisregistraties.overheid.nl/api/v1/' 
        