apiVersion: v1
entries:
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.13.0
    created: "2021-10-05T16:20:01.8699797+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: 1b7c4bfba1e8257793e8d6690e02b86c0bdac99922e1fa74b6a7df9d800938ab
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.10.3.tgz
    version: 10.10.3
  redis:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 6.2.5
    created: "2021-10-05T16:20:01.8841261+02:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      tags:
      - bitnami-common
      version: 1.x.x
    description: Open source, advanced key-value store. It is often referred to as
      a data structure server since keys can contain strings, hashes, lists, sets
      and sorted sets.
    digest: f8fa3b0bdaecf7f9aa1669b027c5452f7efaab21c10b0dbcf7148e17c54ac5b7
    home: https://github.com/bitnami/charts/tree/master/bitnami/redis
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: redis
    sources:
    - https://github.com/bitnami/bitnami-docker-redis
    - http://redis.io/
    urls:
    - charts/redis-15.3.2.tgz
    version: 15.3.2
  verzoekregistratiecomponent:
  - annotations:
      artifacthub.io/containsSecurityUpdates: "true"
    apiVersion: v2
    appVersion: V1.0
    created: "2021-10-05T16:20:01.8578951+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.10.3
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.3.2
    description: Het Verzoek Registratie Component bevat zowel het eind- als tussenresultaat
      van een proces. Of om het iets simpeler te zeggen een proces schrijft bij iedere
      stap zijn variabelen weg naar een verzoek. Daarmee is het proces stateless en
      het verzoek stateful. In deze zin is een verzoek vergelijkbaar met een proces
      token in bijvoorbeeld BPMN- engines. Hierdoor is het mogelijk om verzoeken uit
      te wisselen tussen processen. Het is bijvoorbeeld mogelijk om via een chatbot
      een proces te draaien dat het verzoektype verhuizen gebruikt om een verzoek
      aan te maken, maar het ondertekenen van dit verzoek te laten doen via het webformulier.
    digest: fda5a23cece69b72e5b29c2d465f375b41d50d3468c3a1ade4b3248ea6a3c2ed
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: verzoekregistratiecomponent
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - verzoekregistratiecomponent-1.1.0.tgz
    version: 1.1.0
  - annotations:
      artifacthub.io/containsSecurityUpdates: "true"
    apiVersion: v2
    appVersion: V1.0
    created: "2021-10-05T16:20:01.8379535+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 12.7.7
    description: Het Verzoek Registratie Component bevat zowel het eind- als tussenresultaat
      van een proces. Of om het iets simpeler te zeggen een proces schrijft bij iedere
      stap zijn variabelen weg naar een verzoek. Daarmee is het proces stateless en
      het verzoek stateful. In deze zin is een verzoek vergelijkbaar met een proces
      token in bijvoorbeeld BPMN- engines. Hierdoor is het mogelijk om verzoeken uit
      te wisselen tussen processen. Het is bijvoorbeeld mogelijk om via een chatbot
      een proces te draaien dat het verzoektype verhuizen gebruikt om een verzoek
      aan te maken, maar het ondertekenen van dit verzoek te laten doen via het webformulier.
    digest: 8b4c2177e6a097d204f806e77265e662c2be0c3492a9855747392d6763577b1a
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: verzoekregistratiecomponent
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - verzoekregistratiecomponent-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-10-05T16:20:01.8189223+02:00"
    description: Het Verzoek Registratie Component bevat zowel het eind- als tussenresultaat
      van een proces. Of om het iets simpeler te zeggen een proces schrijft bij iedere
      stap zijn variabelen weg naar een verzoek. Daarmee is het proces stateless en
      het verzoek stateful. In deze zin is een verzoek vergelijkbaar met een proces
      token in bijvoorbeeld BPMN- engines. Hierdoor is het mogelijk om verzoeken uit
      te wisselen tussen processen. Het is bijvoorbeeld mogelijk om via een chatbot
      een proces te draaien dat het verzoektype verhuizen gebruikt om een verzoek
      aan te maken, maar het ondertekenen van dit verzoek te laten doen via het webformulier.
    digest: 03fd140223cb2e863e5c0e66fc0cac232d96386ae3e50a425279c44f2badbe8a
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: verzoekregistratiecomponent
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - verzoekregistratiecomponent-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-05T16:20:01.8074803+02:00"
